### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'insertOne')

### ISSUE THREAD

**Issue by fnLog0** [mjwheatley/graphql-mongodb-subscriptions#45]
Getting this issue while using with apollo server

`TypeError: Cannot read properties of undefined (reading 'insertOne')
    at Channel.publish (/realm-graphql-sub/node_modules/@mawhea/mongopubsub/dist/channel.js:28:32)
    at MongodbPubSub.<anonymous> (/node_modules/graphql-mongodb-subscriptions/dist/mongodb-pub-sub.js:83:49)
    at step (/node_modules/graphql-mongodb-subscriptions/dist/mongodb-pub-sub.js:44:23)
    at Object.next (/Users/nasimakhtar/Projects/effortless/realm-graphql-sub/node_modules/graphql-mongodb-subscriptions/dist/mongodb-pub-sub.js:25:53)`

**Comment by fnLog0** [comment]
`  const realmClient = new MongoClient(process.env.MONGO_DB_URI_EMBEDDING!);
  const realmDb = realmClient.db(process.env.MONGO_DB_NAME!);
  await realmClient.connect();

  async function context() {
    const pubsub = new MongodbPubSub({
      connectionDb: realmDb,
      channelName: "graphql",
      connectionListener: (event, data) => {
        console.log(`MongodbPubSub connectionListener`, { event, data });
      },
    });
    return { pubsub };
  }`

**Comment by fnLog0** [comment]
```
 const realmClient = new MongoClient(process.env.MONGO_DB_URI_EMBEDDING!);
  const realmDb = realmClient.db(process.env.MONGO_DB_NAME!);
  await realmClient.connect();

  async function context() {
    const pubsub = new MongodbPubSub({
      connectionDb: realmDb,
      channelName: "graphql",
      connectionListener: (event, data) => {
        console.log(`MongodbPubSub connectionListener`, { event, data });
      },
    });
    return { pubsub };
  }
```
